export const STYLE_TEMPLATES = [
  // ── Existants (enrichis) ──────────────────────────────────────
  {
    id: 'dark_neon',
    name: 'Dark Neon',
    preview: ['#0d0d1a', '#a78bfa'],
    config: {
      accentColor: '#a78bfa', secondaryColor: '#f472b6', fontColor: '#ffffff',
      bgBrightness: 0.2, cardStyle: 'neon', cardFont: "'Space Mono', monospace",
      cardBgColor: '#0d0d1a', cardBorderColor: '#a78bfa',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['zoom', 'flash', 'glitch'],
      vinylColorMode: 'gradient', showScanlines: true,
      colorFilter: 'none', colorFilterIntensity: 0.15, vignetteIntensity: 0.3,
    },
  },
  {
    id: 'lofi_warm',
    name: 'Lo-Fi Warm',
    preview: ['#1a1008', '#f59e0b'],
    config: {
      accentColor: '#f59e0b', secondaryColor: '#fbbf24', fontColor: '#fef3c7',
      bgBrightness: 0.25, cardStyle: 'glass', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#1a1008', cardBorderColor: '#f59e0b',
      showParticles: true, showBlob: false, showEqualizer: true,
      beatEffects: false, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'solid', showScanlines: false,
      colorFilter: 'warm', colorFilterIntensity: 0.15, vignetteIntensity: 0.3,
    },
  },
  {
    id: 'minimal_white',
    name: 'Minimal',
    preview: ['#0a0a0a', '#e2e8f0'],
    config: {
      accentColor: '#e2e8f0', secondaryColor: '#94a3b8', fontColor: '#ffffff',
      bgBrightness: 0.1, cardStyle: 'minimal', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#0a0a0a', cardBorderColor: '#e2e8f0',
      showParticles: false, showBlob: false, showEqualizer: false,
      beatEffects: false, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'solid', showScanlines: false,
      colorFilter: 'none', colorFilterIntensity: 0.0, vignetteIntensity: 0.1,
    },
  },
  {
    id: 'retro_arcade',
    name: 'Retro Arcade',
    preview: ['#0a0a12', '#00ff88'],
    config: {
      accentColor: '#00ff88', secondaryColor: '#00ffcc', fontColor: '#00ff88',
      bgBrightness: 0.15, cardStyle: 'neon', cardFont: "'Space Mono', monospace",
      cardBgColor: '#0a0a12', cardBorderColor: '#00ff88',
      showParticles: true, showBlob: false, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['zoom', 'flash', 'glitch'],
      vinylColorMode: 'gradient', showScanlines: true,
      colorFilter: 'none', colorFilterIntensity: 0.0, vignetteIntensity: 0.2,
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    preview: ['#0d0020', '#ff2d78'],
    config: {
      accentColor: '#ff2d78', secondaryColor: '#bd5fff', fontColor: '#ffffff',
      bgBrightness: 0.2, cardStyle: 'glass', cardFont: "'Space Mono', monospace",
      cardBgColor: '#0d0020', cardBorderColor: '#ff2d78',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['zoom', 'flash'],
      vinylColorMode: 'gradient', showScanlines: true,
      colorFilter: 'neon', colorFilterIntensity: 0.15, vignetteIntensity: 0.35,
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    preview: ['#020c18', '#38bdf8'],
    config: {
      accentColor: '#38bdf8', secondaryColor: '#0ea5e9', fontColor: '#e0f2fe',
      bgBrightness: 0.2, cardStyle: 'glass', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#020c18', cardBorderColor: '#38bdf8',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'gradient', showScanlines: false,
      colorFilter: 'cold', colorFilterIntensity: 0.1, vignetteIntensity: 0.25,
    },
  },

  // ── Nouveaux thèmes ───────────────────────────────────────────
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    preview: ['#0d0020', '#ff2d78'],
    config: {
      accentColor: '#ff2d78', secondaryColor: '#00f5ff', fontColor: '#ffffff',
      bgBrightness: 0.15, cardStyle: 'neon', cardFont: "'Space Mono', monospace",
      cardBgColor: '#0d0020', cardBorderColor: '#ff2d78',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['glitch', 'flash', 'zoom'],
      vinylColorMode: 'gradient', showScanlines: true,
      colorFilter: 'neon', colorFilterIntensity: 0.2, vignetteIntensity: 0.4,
    },
  },
  {
    id: 'dark_fantasy',
    name: 'Dark Fantasy',
    preview: ['#1e0a2e', '#7c3aed'],
    config: {
      accentColor: '#7c3aed', secondaryColor: '#c084fc', fontColor: '#e9d5ff',
      bgBrightness: 0.12, cardStyle: 'cinematic', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#1e0a2e', cardBorderColor: '#7c3aed',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['zoom', 'flash'],
      vinylColorMode: 'gradient', showScanlines: false,
      colorFilter: 'cold', colorFilterIntensity: 0.12, vignetteIntensity: 0.5,
    },
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    preview: ['#1a0a1e', '#ff71ce'],
    config: {
      accentColor: '#ff71ce', secondaryColor: '#01cdfe', fontColor: '#ffffff',
      bgBrightness: 0.2, cardStyle: 'glass', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#1a0a1e', cardBorderColor: '#ff71ce',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'gradient', showScanlines: true,
      colorFilter: 'pastel', colorFilterIntensity: 0.15, vignetteIntensity: 0.25,
    },
  },
  {
    id: 'horror',
    name: 'Horror',
    preview: ['#0d0000', '#dc2626'],
    config: {
      accentColor: '#dc2626', secondaryColor: '#991b1b', fontColor: '#fca5a5',
      bgBrightness: 0.1, cardStyle: 'minimal', cardFont: "'Space Mono', monospace",
      cardBgColor: '#0d0000', cardBorderColor: '#dc2626',
      showParticles: false, showBlob: false, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['glitch', 'shake', 'flash'],
      vinylColorMode: 'solid', showScanlines: true,
      colorFilter: 'vintage', colorFilterIntensity: 0.3, vignetteIntensity: 0.6,
    },
  },
  {
    id: 'zen',
    name: 'Zen Garden',
    preview: ['#042010', '#22c55e'],
    config: {
      accentColor: '#22c55e', secondaryColor: '#86efac', fontColor: '#dcfce7',
      bgBrightness: 0.22, cardStyle: 'glass', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#042010', cardBorderColor: '#22c55e',
      showParticles: false, showBlob: true, showEqualizer: false,
      beatEffects: false, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'solid', showScanlines: false,
      colorFilter: 'warm', colorFilterIntensity: 0.08, vignetteIntensity: 0.15,
    },
  },
  {
    id: 'jazz',
    name: 'Jazz Club',
    preview: ['#1c0d00', '#d97706'],
    config: {
      accentColor: '#d97706', secondaryColor: '#fbbf24', fontColor: '#fef3c7',
      bgBrightness: 0.18, cardStyle: 'split', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#1c0d00', cardBorderColor: '#d97706',
      showParticles: true, showBlob: false, showEqualizer: true,
      beatEffects: true, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'solid', showScanlines: true,
      colorFilter: 'warm', colorFilterIntensity: 0.25, vignetteIntensity: 0.45,
    },
  },
  {
    id: 'deep_space',
    name: 'Deep Space',
    preview: ['#030418', '#6366f1'],
    config: {
      accentColor: '#6366f1', secondaryColor: '#818cf8', fontColor: '#e0e7ff',
      bgBrightness: 0.1, cardStyle: 'cinematic', cardFont: "'Space Mono', monospace",
      cardBgColor: '#030418', cardBorderColor: '#6366f1',
      showParticles: true, showBlob: true, showEqualizer: true,
      beatEffects: true, beatSyncEffects: true, beatSyncTypes: ['zoom', 'flash'],
      vinylColorMode: 'gradient', showScanlines: false,
      colorFilter: 'cold', colorFilterIntensity: 0.15, vignetteIntensity: 0.5,
    },
  },
  {
    id: 'pastel_dream',
    name: 'Pastel Dream',
    preview: ['#1a0a1a', '#f472b6'],
    config: {
      accentColor: '#f472b6', secondaryColor: '#c084fc', fontColor: '#fce7f3',
      bgBrightness: 0.25, cardStyle: 'glass', cardFont: "'Outfit', sans-serif",
      cardBgColor: '#1a0a1a', cardBorderColor: '#f472b6',
      showParticles: true, showBlob: true, showEqualizer: false,
      beatEffects: false, beatSyncEffects: false, beatSyncTypes: ['zoom'],
      vinylColorMode: 'gradient', showScanlines: false,
      colorFilter: 'pastel', colorFilterIntensity: 0.12, vignetteIntensity: 0.1,
    },
  },
];
